//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Common/InputActions/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""Keyboard"",
            ""id"": ""8857583a-2809-4ad8-a00e-ad4db0997474"",
            ""actions"": [
                {
                    ""name"": ""LeftPress"",
                    ""type"": ""Button"",
                    ""id"": ""f5ec1dee-a342-471c-8ceb-e013c19f5e94"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftRelease"",
                    ""type"": ""Button"",
                    ""id"": ""241b1264-bc74-4fbf-bdc9-ad71f1940367"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPress"",
                    ""type"": ""Button"",
                    ""id"": ""4703378f-5867-4121-8e59-95b632a2c4e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightRelease"",
                    ""type"": ""Button"",
                    ""id"": ""e895b5f7-34a2-4c7b-bab2-1a43c7f83790"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpaceTap"",
                    ""type"": ""Button"",
                    ""id"": ""3fb4eaff-6db6-4f46-bc6f-87b81c2e164a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""662f44d9-714d-4f25-ac73-b1c3979a805c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efab2920-cc29-413a-b149-459e4d47e97f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1d0a1b3-1d37-42c8-87f4-f8c2b2629c45"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4645670-96f1-4db0-b23d-77a10d8a99d5"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b8c0de5-2776-4e7d-95de-aaacbfdd5b0b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpaceTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f33efad-afbd-4e0c-8544-2e6a7ecf285d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed0aa04d-a168-4085-b9a4-eae356f54fe3"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aca9dc3a-9d7e-472a-9a1c-736e442e29e3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b40d7e97-dee6-4079-8dca-9ea1c31b2573"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Keyboard
        m_Keyboard = asset.FindActionMap("Keyboard", throwIfNotFound: true);
        m_Keyboard_LeftPress = m_Keyboard.FindAction("LeftPress", throwIfNotFound: true);
        m_Keyboard_LeftRelease = m_Keyboard.FindAction("LeftRelease", throwIfNotFound: true);
        m_Keyboard_RightPress = m_Keyboard.FindAction("RightPress", throwIfNotFound: true);
        m_Keyboard_RightRelease = m_Keyboard.FindAction("RightRelease", throwIfNotFound: true);
        m_Keyboard_SpaceTap = m_Keyboard.FindAction("SpaceTap", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Keyboard
    private readonly InputActionMap m_Keyboard;
    private List<IKeyboardActions> m_KeyboardActionsCallbackInterfaces = new List<IKeyboardActions>();
    private readonly InputAction m_Keyboard_LeftPress;
    private readonly InputAction m_Keyboard_LeftRelease;
    private readonly InputAction m_Keyboard_RightPress;
    private readonly InputAction m_Keyboard_RightRelease;
    private readonly InputAction m_Keyboard_SpaceTap;
    public struct KeyboardActions
    {
        private @PlayerActions m_Wrapper;
        public KeyboardActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftPress => m_Wrapper.m_Keyboard_LeftPress;
        public InputAction @LeftRelease => m_Wrapper.m_Keyboard_LeftRelease;
        public InputAction @RightPress => m_Wrapper.m_Keyboard_RightPress;
        public InputAction @RightRelease => m_Wrapper.m_Keyboard_RightRelease;
        public InputAction @SpaceTap => m_Wrapper.m_Keyboard_SpaceTap;
        public InputActionMap Get() { return m_Wrapper.m_Keyboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyboardActions set) { return set.Get(); }
        public void AddCallbacks(IKeyboardActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyboardActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyboardActionsCallbackInterfaces.Add(instance);
            @LeftPress.started += instance.OnLeftPress;
            @LeftPress.performed += instance.OnLeftPress;
            @LeftPress.canceled += instance.OnLeftPress;
            @LeftRelease.started += instance.OnLeftRelease;
            @LeftRelease.performed += instance.OnLeftRelease;
            @LeftRelease.canceled += instance.OnLeftRelease;
            @RightPress.started += instance.OnRightPress;
            @RightPress.performed += instance.OnRightPress;
            @RightPress.canceled += instance.OnRightPress;
            @RightRelease.started += instance.OnRightRelease;
            @RightRelease.performed += instance.OnRightRelease;
            @RightRelease.canceled += instance.OnRightRelease;
            @SpaceTap.started += instance.OnSpaceTap;
            @SpaceTap.performed += instance.OnSpaceTap;
            @SpaceTap.canceled += instance.OnSpaceTap;
        }

        private void UnregisterCallbacks(IKeyboardActions instance)
        {
            @LeftPress.started -= instance.OnLeftPress;
            @LeftPress.performed -= instance.OnLeftPress;
            @LeftPress.canceled -= instance.OnLeftPress;
            @LeftRelease.started -= instance.OnLeftRelease;
            @LeftRelease.performed -= instance.OnLeftRelease;
            @LeftRelease.canceled -= instance.OnLeftRelease;
            @RightPress.started -= instance.OnRightPress;
            @RightPress.performed -= instance.OnRightPress;
            @RightPress.canceled -= instance.OnRightPress;
            @RightRelease.started -= instance.OnRightRelease;
            @RightRelease.performed -= instance.OnRightRelease;
            @RightRelease.canceled -= instance.OnRightRelease;
            @SpaceTap.started -= instance.OnSpaceTap;
            @SpaceTap.performed -= instance.OnSpaceTap;
            @SpaceTap.canceled -= instance.OnSpaceTap;
        }

        public void RemoveCallbacks(IKeyboardActions instance)
        {
            if (m_Wrapper.m_KeyboardActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKeyboardActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyboardActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyboardActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KeyboardActions @Keyboard => new KeyboardActions(this);
    public interface IKeyboardActions
    {
        void OnLeftPress(InputAction.CallbackContext context);
        void OnLeftRelease(InputAction.CallbackContext context);
        void OnRightPress(InputAction.CallbackContext context);
        void OnRightRelease(InputAction.CallbackContext context);
        void OnSpaceTap(InputAction.CallbackContext context);
    }
}
